
/* Drop Triggers */

DROP TRIGGER TRI_AUCTION_A_NUM;
DROP TRIGGER TRI_BID_BID_NUMBER;
DROP TRIGGER TRI_BOARD_B_NUM;
DROP TRIGGER TRI_CATEGORY_C_NUM;
DROP TRIGGER TRI_MEMBERS_M_NUM;
DROP TRIGGER TRI_MEMBER_M_NUM;
DROP TRIGGER TRI_PAYMENT_PAY_NUM;
DROP TRIGGER TRI_QNA_QNA_NUM;
DROP TRIGGER TRI_QUESTION_QNA_NUM;
DROP TRIGGER TRI_QUESTION_QUE_NUM;
DROP TRIGGER TRI_SELLER_SEL_NUMBER;
DROP TRIGGER TRI_SHIP_S_NUM;
DROP TRIGGER TRI_SINGO_PENALTY_NUM;
DROP TRIGGER TRI_SINGO_SINGO_NUM;



/* Drop Tables */

DROP TABLE ADMINISTRATOR CASCADE CONSTRAINTS;
DROP TABLE ANSWER CASCADE CONSTRAINTS;
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
DROP TABLE BID CASCADE CONSTRAINTS;
DROP TABLE IMG CASCADE CONSTRAINTS;
DROP TABLE INTERPRODUCT CASCADE CONSTRAINTS;
DROP TABLE QUESTION CASCADE CONSTRAINTS;
DROP TABLE AUCTION CASCADE CONSTRAINTS;
DROP TABLE B_ANSWER CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE SINGO CASCADE CONSTRAINTS;
DROP TABLE SELLER CASCADE CONSTRAINTS;
DROP TABLE MEMBERS CASCADE CONSTRAINTS;
DROP TABLE SHIP CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE SEQ_AUCTION_A_NUM;
DROP SEQUENCE SEQ_BID_BID_NUMBER;
DROP SEQUENCE SEQ_BOARD_B_NUM;
DROP SEQUENCE SEQ_CATEGORY_C_NUM;
DROP SEQUENCE SEQ_MEMBERS_M_NUM;
DROP SEQUENCE SEQ_MEMBER_M_NUM;
DROP SEQUENCE SEQ_PAYMENT_PAY_NUM;
DROP SEQUENCE SEQ_QNA_QNA_NUM;
DROP SEQUENCE SEQ_QUESTION_QNA_NUM;
DROP SEQUENCE SEQ_QUESTION_QUE_NUM;
DROP SEQUENCE SEQ_SELLER_SEL_NUMBER;
DROP SEQUENCE SEQ_SHIP_S_NUM;
DROP SEQUENCE SEQ_SINGO_PENALTY_NUM;
DROP SEQUENCE SEQ_SINGO_SINGO_NUM;




/* Create Sequences */

CREATE SEQUENCE SEQ_AUCTION_A_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_BID_BID_NUMBER INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_BOARD_B_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_CATEGORY_C_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_MEMBERS_M_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_MEMBER_M_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_PAYMENT_PAY_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_QNA_QNA_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_QUESTION_QNA_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_QUESTION_QUE_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_SELLER_SEL_NUMBER INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_SHIP_S_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_SINGO_PENALTY_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_SINGO_SINGO_NUM INCREMENT BY 1 START WITH 1;



/* Create Tables */

-- 관리자
CREATE TABLE ADMINISTRATOR
(
	-- 관리자아이디
	ADM_ID varchar2(10) NOT NULL UNIQUE,
	-- ADM_PWD
	ADM_PWD varchar2(20) NOT NULL,
	PRIMARY KEY (ADM_ID)
);


-- 답변
CREATE TABLE ANSWER
(
	-- 문의게시판 번호
	QUE_NUM number(5) NOT NULL,
	-- 답변 : 제목은 답변입니다로 통일
	B_CONTENT varchar2(1000) NOT NULL
);


-- 경매
CREATE TABLE AUCTION
(
	-- 경매번호
	A_NUM number(5,0) NOT NULL,
	-- 경매제목
	A_TITLE varchar2(100) NOT NULL,
	-- 경매내용
	A_CONTNET varchar2(1000) NOT NULL,
	-- 상품상태
	A_CONDITION number(1) NOT NULL,
	-- 등록일자
	A_REGDATE date NOT NULL,
	-- 경매시작시간
	A_STARTDATE date NOT NULL,
	-- 마감시간
	A_ENDDATE date NOT NULL,
	-- 조회수
	A_CHECK number(5) DEFAULT 0 NOT NULL,
	-- 카테고리넘버
	C_NUM number(2) NOT NULL,
	-- 찜
	A_JJIM number(5) DEFAULT 0 NOT NULL,
	-- 배송번호
	S_NUM number(5) NOT NULL,
	-- 판매자번호
	SEL_NUMBER number(5) NOT NULL,
	-- 경매상태 : 0 : 입찰전
	-- 1 : 입찰중
	-- 2 : 거래중
	-- 3 : 거래완료
	BIDSTATUS number(1) DEFAULT 0 NOT NULL,
	-- A_STARTBID
	A_STARTBID number(8) DEFAULT 0 NOT NULL,
	-- 입찰단위 : 경매 입찰 단위
	A_BIDUNIT number(7) DEFAULT 0 NOT NULL,
	PRIMARY KEY (A_NUM)
);


-- 입찰
CREATE TABLE BID
(
	-- 회원번호
	M_NUM number(5,0) NOT NULL,
	-- 경매번호
	A_NUM number(5,0) NOT NULL,
	-- 입찰가격
	BID_PRICE number(8) NOT NULL UNIQUE,
	-- 입찰시간 : SYSTIMESTAMP
	BID_DATE date NOT NULL,
	-- 입찰번호
	BID_NUMBER number(5) NOT NULL,
	PRIMARY KEY (BID_NUMBER)
);


-- 문의사항
CREATE TABLE BOARD
(
	-- 게시판 번호
	B_NUM number(5) NOT NULL,
	-- BOARD TITLE
	B_TITLE varchar2(100) NOT NULL,
	-- BORAD CONTENT
	B_CONTNENT varchar2(1000) NOT NULL,
	-- BORAD STATUS : 0 : 미답변
	-- 1 : 완료
	B_STATUS number(1),
	-- 회원번호
	M_NUM number(5,0) NOT NULL,
	-- 문의날짜
	B_REGDATE date,
	PRIMARY KEY (B_NUM)
);


-- 답변
CREATE TABLE B_ANSWER
(
	-- 답변 : 제목은 답변입니다로 통일
	B_CONTENT varchar2(1000) NOT NULL,
	-- 게시판 번호
	B_NUM number(5) NOT NULL,
	-- 답변날짜
	ANSWERDATE date
);


-- 카테고리
CREATE TABLE CATEGORY
(
	-- 카테고리넘버
	C_NUM number(2) NOT NULL,
	-- 카테고리 설명
	C_DES varchar2(20) NOT NULL UNIQUE,
	PRIMARY KEY (C_NUM)
);


-- 이미지
CREATE TABLE IMG
(
	-- 경매번호
	A_NUM number(5,0) NOT NULL,
	-- I_PATH
	I_PATH varchar2(500)
);


-- 관심상품
CREATE TABLE INTERPRODUCT
(
	-- 회원번호
	M_NUM number(5,0) NOT NULL,
	-- 경매번호
	A_NUM number(5,0) NOT NULL
);


-- 회원
CREATE TABLE MEMBERS
(
	-- 회원번호
	M_NUM number(5,0) NOT NULL,
	-- 회원이름
	M_NAME varchar2(14) NOT NULL,
	-- 이메일
	M_EMAIL varchar2(50) NOT NULL UNIQUE,
	-- 회원전화번호
	M_PHONE number(13),
	-- 회원주소
	M_ADDR varchar2(100) NOT NULL,
	-- 회원아이디 : 영어랑 숫자만 입력가능
	-- (최소 6, 최대 12글자)
	M_ID varchar2(12) NOT NULL UNIQUE,
	-- 회원비밀번호
	M_PWD varchar2(30) NOT NULL,
	-- 신뢰도 : 신뢰도 시작 : 5
	-- 정상거래시 +1
	-- 신고 및 비매너 거래 -1
	TRUST number(3) DEFAULT 5 NOT NULL,
	-- 회원타입 : 0:회원
	-- 1:탈퇴한 회원
	M_TYPE number(1) DEFAULT 0 NOT NULL,
	-- 회원 가입일
	M_REGDATE date NOT NULL,
	PRIMARY KEY (M_NUM)
);


-- 지불
CREATE TABLE PAYMENT
(
	-- 지불 번호
	PAY_NUM number(5) NOT NULL,
	-- 배송지
	PAY_ADDR varchar2(500) NOT NULL,
	-- 입금상태 : 0: 미입금
	-- 1 : 입금완료
	PAY_STATUS number(1) DEFAULT 0 NOT NULL,
	-- 입찰번호
	BID_NUMBER number(5) NOT NULL,
	PRIMARY KEY (PAY_NUM)
);


-- 문의게시판
CREATE TABLE QUESTION
(
	-- 문의게시판 번호
	QUE_NUM number(5) NOT NULL,
	-- 문의게시판 제목
	QUE_TITLE varchar2(100) NOT NULL,
	-- 문의게시판 문의내용
	QUE_CONTNET varchar2(1000) NOT NULL,
	-- 회원번호
	M_NUM number(5,0) NOT NULL,
	-- 경매번호
	A_NUM number(5,0) NOT NULL,
	-- 답변,미답변 구분 : 미답변 : 0
	-- 답변 : 1
	QUE_STATUS number(1) DEFAULT 0 NOT NULL,
	-- 등록날짜
	QUE_REGDATE date NOT NULL,
	PRIMARY KEY (QUE_NUM)
);


-- 판매자 계좌번호
CREATE TABLE SELLER
(
	-- ACCOUNT
	ACCOUNT number(13) NOT NULL,
	-- 회원번호
	M_NUM number(5,0) NOT NULL,
	-- 판매자번호
	SEL_NUMBER number(5) NOT NULL,
	PRIMARY KEY (SEL_NUMBER)
);


-- 배송방법
CREATE TABLE SHIP
(
	-- 배송번호
	S_NUM number(5) NOT NULL,
	-- 배송방법
	S_WAY varchar2(20),
	-- 택배비
	S_PRICE number(6) DEFAULT 0,
	PRIMARY KEY (S_NUM)
);


-- 신고
CREATE TABLE SINGO
(
	-- 판매자번호
	SEL_NUMBER number(5) NOT NULL,
	-- 회원번호
	M_NUM number(5,0) NOT NULL,
	-- 신고번호
	SINGO_NUM number(5) NOT NULL,
	-- 신고내용
	SINGO_CONTENT varchar2(500) NOT NULL,
	-- 신고상태 : 0 : 처리전
	-- 1 : 처리함
	-- 2 : 처리 반려
	SINGO_STATUS number(1) DEFAULT 0 NOT NULL,
	-- 신고한 날짜 : 신고한 날짜
	SINGO_DATE date NOT NULL,
	PRIMARY KEY (SINGO_NUM)
);



/* Create Foreign Keys */

ALTER TABLE BID
	ADD FOREIGN KEY (A_NUM)
	REFERENCES AUCTION (A_NUM)
;


ALTER TABLE IMG
	ADD FOREIGN KEY (A_NUM)
	REFERENCES AUCTION (A_NUM)
;


ALTER TABLE INTERPRODUCT
	ADD FOREIGN KEY (A_NUM)
	REFERENCES AUCTION (A_NUM)
;


ALTER TABLE QUESTION
	ADD FOREIGN KEY (A_NUM)
	REFERENCES AUCTION (A_NUM)
;


ALTER TABLE PAYMENT
	ADD FOREIGN KEY (BID_NUMBER)
	REFERENCES BID (BID_NUMBER)
;


ALTER TABLE B_ANSWER
	ADD FOREIGN KEY (B_NUM)
	REFERENCES BOARD (B_NUM)
;


ALTER TABLE AUCTION
	ADD FOREIGN KEY (C_NUM)
	REFERENCES CATEGORY (C_NUM)
;


ALTER TABLE BID
	ADD FOREIGN KEY (M_NUM)
	REFERENCES MEMBERS (M_NUM)
;


ALTER TABLE BOARD
	ADD FOREIGN KEY (M_NUM)
	REFERENCES MEMBERS (M_NUM)
;


ALTER TABLE INTERPRODUCT
	ADD FOREIGN KEY (M_NUM)
	REFERENCES MEMBERS (M_NUM)
;


ALTER TABLE QUESTION
	ADD FOREIGN KEY (M_NUM)
	REFERENCES MEMBERS (M_NUM)
;


ALTER TABLE SELLER
	ADD FOREIGN KEY (M_NUM)
	REFERENCES MEMBERS (M_NUM)
;


ALTER TABLE SINGO
	ADD FOREIGN KEY (M_NUM)
	REFERENCES MEMBERS (M_NUM)
;


ALTER TABLE ANSWER
	ADD FOREIGN KEY (QUE_NUM)
	REFERENCES QUESTION (QUE_NUM)
;


ALTER TABLE AUCTION
	ADD FOREIGN KEY (SEL_NUMBER)
	REFERENCES SELLER (SEL_NUMBER)
;


ALTER TABLE SINGO
	ADD FOREIGN KEY (SEL_NUMBER)
	REFERENCES SELLER (SEL_NUMBER)
;


ALTER TABLE AUCTION
	ADD FOREIGN KEY (S_NUM)
	REFERENCES SHIP (S_NUM)
;



/* Create Triggers */

CREATE OR REPLACE TRIGGER TRI_AUCTION_A_NUM BEFORE INSERT ON AUCTION
FOR EACH ROW
BEGIN
	SELECT SEQ_AUCTION_A_NUM.nextval
	INTO :new.A_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_BID_BID_NUMBER BEFORE INSERT ON BID
FOR EACH ROW
BEGIN
	SELECT SEQ_BID_BID_NUMBER.nextval
	INTO :new.BID_NUMBER
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_BOARD_B_NUM BEFORE INSERT ON BOARD
FOR EACH ROW
BEGIN
	SELECT SEQ_BOARD_B_NUM.nextval
	INTO :new.B_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_CATEGORY_C_NUM BEFORE INSERT ON CATEGORY
FOR EACH ROW
BEGIN
	SELECT SEQ_CATEGORY_C_NUM.nextval
	INTO :new.C_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_MEMBERS_M_NUM BEFORE INSERT ON MEMBERS
FOR EACH ROW
BEGIN
	SELECT SEQ_MEMBERS_M_NUM.nextval
	INTO :new.M_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_MEMBER_M_NUM BEFORE INSERT ON MEMBER
FOR EACH ROW
BEGIN
	SELECT SEQ_MEMBER_M_NUM.nextval
	INTO :new.M_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_PAYMENT_PAY_NUM BEFORE INSERT ON PAYMENT
FOR EACH ROW
BEGIN
	SELECT SEQ_PAYMENT_PAY_NUM.nextval
	INTO :new.PAY_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_QNA_QNA_NUM BEFORE INSERT ON QNA
FOR EACH ROW
BEGIN
	SELECT SEQ_QNA_QNA_NUM.nextval
	INTO :new.QNA_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_QUESTION_QNA_NUM BEFORE INSERT ON QUESTION
FOR EACH ROW
BEGIN
	SELECT SEQ_QUESTION_QNA_NUM.nextval
	INTO :new.QNA_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_QUESTION_QUE_NUM BEFORE INSERT ON QUESTION
FOR EACH ROW
BEGIN
	SELECT SEQ_QUESTION_QUE_NUM.nextval
	INTO :new.QUE_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_SELLER_SEL_NUMBER BEFORE INSERT ON SELLER
FOR EACH ROW
BEGIN
	SELECT SEQ_SELLER_SEL_NUMBER.nextval
	INTO :new.SEL_NUMBER
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_SHIP_S_NUM BEFORE INSERT ON SHIP
FOR EACH ROW
BEGIN
	SELECT SEQ_SHIP_S_NUM.nextval
	INTO :new.S_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_SINGO_PENALTY_NUM BEFORE INSERT ON SINGO
FOR EACH ROW
BEGIN
	SELECT SEQ_SINGO_PENALTY_NUM.nextval
	INTO :new.PENALTY_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_SINGO_SINGO_NUM BEFORE INSERT ON SINGO
FOR EACH ROW
BEGIN
	SELECT SEQ_SINGO_SINGO_NUM.nextval
	INTO :new.SINGO_NUM
	FROM dual;
END;

/




/* Comments */

COMMENT ON TABLE ADMINISTRATOR IS '관리자';
COMMENT ON COLUMN ADMINISTRATOR.ADM_ID IS '관리자아이디';
COMMENT ON COLUMN ADMINISTRATOR.ADM_PWD IS 'ADM_PWD';
COMMENT ON TABLE ANSWER IS '답변';
COMMENT ON COLUMN ANSWER.QUE_NUM IS '문의게시판 번호';
COMMENT ON COLUMN ANSWER.B_CONTENT IS '답변 : 제목은 답변입니다로 통일';
COMMENT ON TABLE AUCTION IS '경매';
COMMENT ON COLUMN AUCTION.A_NUM IS '경매번호';
COMMENT ON COLUMN AUCTION.A_TITLE IS '경매제목';
COMMENT ON COLUMN AUCTION.A_CONTNET IS '경매내용';
COMMENT ON COLUMN AUCTION.A_CONDITION IS '상품상태';
COMMENT ON COLUMN AUCTION.A_REGDATE IS '등록일자';
COMMENT ON COLUMN AUCTION.A_STARTDATE IS '경매시작시간';
COMMENT ON COLUMN AUCTION.A_ENDDATE IS '마감시간';
COMMENT ON COLUMN AUCTION.A_CHECK IS '조회수';
COMMENT ON COLUMN AUCTION.C_NUM IS '카테고리넘버';
COMMENT ON COLUMN AUCTION.A_JJIM IS '찜';
COMMENT ON COLUMN AUCTION.S_NUM IS '배송번호';
COMMENT ON COLUMN AUCTION.SEL_NUMBER IS '판매자번호';
COMMENT ON COLUMN AUCTION.BIDSTATUS IS '경매상태 : 0 : 입찰전
1 : 입찰중
2 : 거래중
3 : 거래완료';
COMMENT ON COLUMN AUCTION.A_STARTBID IS 'A_STARTBID';
COMMENT ON COLUMN AUCTION.A_BIDUNIT IS '입찰단위 : 경매 입찰 단위';
COMMENT ON TABLE BID IS '입찰';
COMMENT ON COLUMN BID.M_NUM IS '회원번호';
COMMENT ON COLUMN BID.A_NUM IS '경매번호';
COMMENT ON COLUMN BID.BID_PRICE IS '입찰가격';
COMMENT ON COLUMN BID.BID_DATE IS '입찰시간 : SYSTIMESTAMP';
COMMENT ON COLUMN BID.BID_NUMBER IS '입찰번호';
COMMENT ON TABLE BOARD IS '문의사항';
COMMENT ON COLUMN BOARD.B_NUM IS '게시판 번호';
COMMENT ON COLUMN BOARD.B_TITLE IS 'BOARD TITLE';
COMMENT ON COLUMN BOARD.B_CONTNENT IS 'BORAD CONTENT';
COMMENT ON COLUMN BOARD.B_STATUS IS 'BORAD STATUS : 0 : 미답변
1 : 완료';
COMMENT ON COLUMN BOARD.M_NUM IS '회원번호';
COMMENT ON COLUMN BOARD.B_REGDATE IS '문의날짜';
COMMENT ON TABLE B_ANSWER IS '답변';
COMMENT ON COLUMN B_ANSWER.B_CONTENT IS '답변 : 제목은 답변입니다로 통일';
COMMENT ON COLUMN B_ANSWER.B_NUM IS '게시판 번호';
COMMENT ON COLUMN B_ANSWER.ANSWERDATE IS '답변날짜';
COMMENT ON TABLE CATEGORY IS '카테고리';
COMMENT ON COLUMN CATEGORY.C_NUM IS '카테고리넘버';
COMMENT ON COLUMN CATEGORY.C_DES IS '카테고리 설명';
COMMENT ON TABLE IMG IS '이미지';
COMMENT ON COLUMN IMG.A_NUM IS '경매번호';
COMMENT ON COLUMN IMG.I_PATH IS 'I_PATH';
COMMENT ON TABLE INTERPRODUCT IS '관심상품';
COMMENT ON COLUMN INTERPRODUCT.M_NUM IS '회원번호';
COMMENT ON COLUMN INTERPRODUCT.A_NUM IS '경매번호';
COMMENT ON TABLE MEMBERS IS '회원';
COMMENT ON COLUMN MEMBERS.M_NUM IS '회원번호';
COMMENT ON COLUMN MEMBERS.M_NAME IS '회원이름';
COMMENT ON COLUMN MEMBERS.M_EMAIL IS '이메일';
COMMENT ON COLUMN MEMBERS.M_PHONE IS '회원전화번호';
COMMENT ON COLUMN MEMBERS.M_ADDR IS '회원주소';
COMMENT ON COLUMN MEMBERS.M_ID IS '회원아이디 : 영어랑 숫자만 입력가능
(최소 6, 최대 12글자)';
COMMENT ON COLUMN MEMBERS.M_PWD IS '회원비밀번호';
COMMENT ON COLUMN MEMBERS.TRUST IS '신뢰도 : 신뢰도 시작 : 5
정상거래시 +1
신고 및 비매너 거래 -1';
COMMENT ON COLUMN MEMBERS.M_TYPE IS '회원타입 : 0:회원
1:탈퇴한 회원';
COMMENT ON COLUMN MEMBERS.M_REGDATE IS '회원 가입일';
COMMENT ON TABLE PAYMENT IS '지불';
COMMENT ON COLUMN PAYMENT.PAY_NUM IS '지불 번호';
COMMENT ON COLUMN PAYMENT.PAY_ADDR IS '배송지';
COMMENT ON COLUMN PAYMENT.PAY_STATUS IS '입금상태 : 0: 미입금
1 : 입금완료';
COMMENT ON COLUMN PAYMENT.BID_NUMBER IS '입찰번호';
COMMENT ON TABLE QUESTION IS '문의게시판';
COMMENT ON COLUMN QUESTION.QUE_NUM IS '문의게시판 번호';
COMMENT ON COLUMN QUESTION.QUE_TITLE IS '문의게시판 제목';
COMMENT ON COLUMN QUESTION.QUE_CONTNET IS '문의게시판 문의내용';
COMMENT ON COLUMN QUESTION.M_NUM IS '회원번호';
COMMENT ON COLUMN QUESTION.A_NUM IS '경매번호';
COMMENT ON COLUMN QUESTION.QUE_STATUS IS '답변,미답변 구분 : 미답변 : 0
답변 : 1';
COMMENT ON COLUMN QUESTION.QUE_REGDATE IS '등록날짜';
COMMENT ON TABLE SELLER IS '판매자 계좌번호';
COMMENT ON COLUMN SELLER.ACCOUNT IS 'ACCOUNT';
COMMENT ON COLUMN SELLER.M_NUM IS '회원번호';
COMMENT ON COLUMN SELLER.SEL_NUMBER IS '판매자번호';
COMMENT ON TABLE SHIP IS '배송방법';
COMMENT ON COLUMN SHIP.S_NUM IS '배송번호';
COMMENT ON COLUMN SHIP.S_WAY IS '배송방법';
COMMENT ON COLUMN SHIP.S_PRICE IS '택배비';
COMMENT ON TABLE SINGO IS '신고';
COMMENT ON COLUMN SINGO.SEL_NUMBER IS '판매자번호';
COMMENT ON COLUMN SINGO.M_NUM IS '회원번호';
COMMENT ON COLUMN SINGO.SINGO_NUM IS '신고번호';
COMMENT ON COLUMN SINGO.SINGO_CONTENT IS '신고내용';
COMMENT ON COLUMN SINGO.SINGO_STATUS IS '신고상태 : 0 : 처리전
1 : 처리함
2 : 처리 반려';
COMMENT ON COLUMN SINGO.SINGO_DATE IS '신고한 날짜 : 신고한 날짜';



