
/* Drop Triggers */

DROP TRIGGER TRI_AUCTION_A_NUM;
DROP TRIGGER TRI_BID_BID_NUMBER;
DROP TRIGGER TRI_BOARD_B_NUM;
DROP TRIGGER TRI_CATEGORY_C_NUM;
DROP TRIGGER TRI_MEMBERS_M_NUM;
DROP TRIGGER TRI_MEMBER_M_NUM;
DROP TRIGGER TRI_PAYMENT_PAY_NUM;
DROP TRIGGER TRI_QNA_QNA_NUM;
DROP TRIGGER TRI_QUESTION_QNA_NUM;
DROP TRIGGER TRI_QUESTION_QUE_NUM;
DROP TRIGGER TRI_SELLER_SEL_NUMBER;
DROP TRIGGER TRI_SHIP_S_NUM;
DROP TRIGGER TRI_SINGO_PENALTY_NUM;
DROP TRIGGER TRI_SINGO_SINGO_NUM;



/* Drop Tables */

DROP TABLE ADMINISTRATOR CASCADE CONSTRAINTS;
DROP TABLE ANSWER CASCADE CONSTRAINTS;
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
DROP TABLE BID CASCADE CONSTRAINTS;
DROP TABLE IMG CASCADE CONSTRAINTS;
DROP TABLE INTERPRODUCT CASCADE CONSTRAINTS;
DROP TABLE QUESTION CASCADE CONSTRAINTS;
DROP TABLE SHIP CASCADE CONSTRAINTS;
DROP TABLE AUCTION CASCADE CONSTRAINTS;
DROP TABLE B_ANSWER CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE SINGO CASCADE CONSTRAINTS;
DROP TABLE SELLER CASCADE CONSTRAINTS;
DROP TABLE MEMBERS CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE SEQ_AUCTION_A_NUM;
DROP SEQUENCE SEQ_BID_BID_NUMBER;
DROP SEQUENCE SEQ_BOARD_B_NUM;
DROP SEQUENCE SEQ_CATEGORY_C_NUM;
DROP SEQUENCE SEQ_MEMBERS_M_NUM;
DROP SEQUENCE SEQ_MEMBER_M_NUM;
DROP SEQUENCE SEQ_PAYMENT_PAY_NUM;
DROP SEQUENCE SEQ_QNA_QNA_NUM;
DROP SEQUENCE SEQ_QUESTION_QNA_NUM;
DROP SEQUENCE SEQ_QUESTION_QUE_NUM;
DROP SEQUENCE SEQ_SELLER_SEL_NUMBER;
DROP SEQUENCE SEQ_SHIP_S_NUM;
DROP SEQUENCE SEQ_SINGO_PENALTY_NUM;
DROP SEQUENCE SEQ_SINGO_SINGO_NUM;





/* Create Sequences */

CREATE SEQUENCE SEQ_AUCTION_A_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_BID_BID_NUMBER INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_BOARD_B_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_CATEGORY_C_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_MEMBERS_M_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_MEMBER_M_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_PAYMENT_PAY_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_QNA_QNA_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_QUESTION_QNA_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_QUESTION_QUE_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_SELLER_SEL_NUMBER INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_SHIP_S_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_SINGO_PENALTY_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_SINGO_SINGO_NUM INCREMENT BY 1 START WITH 1;



/* Create Tables */

CREATE TABLE ADMINISTRATOR
(
	ADM_ID varchar2(10) NOT NULL,
	ADM_PWD varchar2(20) NOT NULL,
	PRIMARY KEY (ADM_ID)
);


CREATE TABLE ANSWER
(
	QUE_NUM number(5) NOT NULL,
	-- 제목은 답변입니다로 통일
	B_CONTENT varchar2(1000) NOT NULL
);


CREATE TABLE AUCTION
(
	A_NUM number(5,0) NOT NULL,
	A_TITLE varchar2(100) NOT NULL,
	A_CONTNET varchar2(1000) NOT NULL,
	A_CONDITION number(1) NOT NULL,
	A_REGDATE date NOT NULL,
	A_STARTDATE date NOT NULL,
	A_ENDDATE date NOT NULL,
	A_CHECK number(5) DEFAULT 0 NOT NULL,
	C_NUM number(2) NOT NULL,
	A_JJIM number(5) DEFAULT 0 NOT NULL,
	SEL_NUMBER number(5) NOT NULL,
	-- 0 : 입찰전
	-- 1 : 입찰중
	-- 2 : 거래중
	-- 3 : 거래완료
	BIDSTATUS number(1) DEFAULT 0 NOT NULL,
	A_STARTBID number(8) DEFAULT 0 NOT NULL,
	-- 경매 입찰 단위
	A_BIDUNIT number(7) DEFAULT 0 NOT NULL,
	PRIMARY KEY (A_NUM)
);


CREATE TABLE BID
(
	M_NUM number(5,0) NOT NULL,
	A_NUM number(5,0) NOT NULL,
	BID_PRICE number(8) NOT NULL UNIQUE,
	-- SYSTIMESTAMP
	BID_DATE date NOT NULL,
	BID_NUMBER number(5) NOT NULL,
	PRIMARY KEY (BID_NUMBER)
);


CREATE TABLE BOARD
(
	B_NUM number(5) NOT NULL,
	B_TITLE varchar2(100) NOT NULL,
	B_CONTNENT varchar2(1000) NOT NULL,
	-- 0 : 미답변
	-- 1 : 완료
	B_STATUS number(1),
	M_NUM number(5,0) NOT NULL,
	B_REGDATE date,
	PRIMARY KEY (B_NUM)
);


CREATE TABLE B_ANSWER
(
	-- 제목은 답변입니다로 통일
	B_CONTENT varchar2(1000) NOT NULL,
	B_NUM number(5) NOT NULL,
	ANSWERDATE date
);


CREATE TABLE CATEGORY
(
	C_NUM number(2) NOT NULL,
	C_DES varchar2(20) NOT NULL UNIQUE,
	PRIMARY KEY (C_NUM)
);


CREATE TABLE IMG
(
	A_NUM number(5,0) NOT NULL,
	I_PATH varchar2(500)
);


CREATE TABLE INTERPRODUCT
(
	M_NUM number(5,0) NOT NULL,
	A_NUM number(5,0) NOT NULL
);


CREATE TABLE MEMBERS
(
	M_NUM number(5,0) NOT NULL,
	M_NAME varchar2(14) NOT NULL,
	M_EMAIL varchar2(50) NOT NULL UNIQUE,
	M_PHONE number(13),
	M_ADDR varchar2(100) NOT NULL,
	-- 영어랑 숫자만 입력가능
	-- (최소 6, 최대 12글자)
	M_ID varchar2(12) NOT NULL UNIQUE,
	M_PWD varchar2(30) NOT NULL,
	-- 신뢰도 시작 : 5
	-- 정상거래시 +1
	-- 신고 및 비매너 거래 -1
	TRUST number(3) DEFAULT 5 NOT NULL,
	-- 0:회원
	-- 1:탈퇴한 회원
	M_TYPE number(1) DEFAULT 0 NOT NULL,
	M_REGDATE date NOT NULL,
	PRIMARY KEY (M_NUM)
);


CREATE TABLE PAYMENT
(
	PAY_NUM number(5) NOT NULL,
	PAY_ADDR varchar2(500) NOT NULL,
	-- 0: 미입금
	-- 1 : 입금완료
	PAY_STATUS number(1) DEFAULT 0 NOT NULL,
	BID_NUMBER number(5) NOT NULL,
	PRIMARY KEY (PAY_NUM)
);


CREATE TABLE QUESTION
(
	QUE_NUM number(5) NOT NULL,
	QUE_TITLE varchar2(100) NOT NULL,
	QUE_CONTNET varchar2(1000) NOT NULL,
	M_NUM number(5,0) NOT NULL,
	A_NUM number(5,0) NOT NULL,
	-- 미답변 : 0
	-- 답변 : 1
	QUE_STATUS number(1) DEFAULT 0 NOT NULL,
	QUE_REGDATE date NOT NULL,
	PRIMARY KEY (QUE_NUM)
);


CREATE TABLE SELLER
(
	ACCOUNT number(13) NOT NULL,
	M_NUM number(5,0) NOT NULL,
	SEL_NUMBER number(5) NOT NULL,
	PRIMARY KEY (SEL_NUMBER)
);


CREATE TABLE SHIP
(
	S_NUM number(5) NOT NULL,
	S_WAY varchar2(20),
	S_PRICE number(6) DEFAULT 0,
	A_NUM number(5,0) NOT NULL,
	PRIMARY KEY (S_NUM)
);


CREATE TABLE SINGO
(
	SEL_NUMBER number(5) NOT NULL,
	M_NUM number(5,0) NOT NULL,
	SINGO_NUM number(5) NOT NULL,
	SINGO_CONTENT varchar2(500) NOT NULL,
	-- 0 : 처리전
	-- 1 : 처리함
	-- 2 : 처리 반려
	SINGO_STATUS number(1) DEFAULT 0 NOT NULL,
	-- 신고한 날짜
	SINGO_DATE date NOT NULL,
	PRIMARY KEY (SINGO_NUM)
);



/* Create Foreign Keys */

ALTER TABLE BID
	ADD FOREIGN KEY (A_NUM)
	REFERENCES AUCTION (A_NUM)
;


ALTER TABLE IMG
	ADD FOREIGN KEY (A_NUM)
	REFERENCES AUCTION (A_NUM)
;


ALTER TABLE INTERPRODUCT
	ADD FOREIGN KEY (A_NUM)
	REFERENCES AUCTION (A_NUM)
;


ALTER TABLE QUESTION
	ADD FOREIGN KEY (A_NUM)
	REFERENCES AUCTION (A_NUM)
;


ALTER TABLE SHIP
	ADD FOREIGN KEY (A_NUM)
	REFERENCES AUCTION (A_NUM)
;


ALTER TABLE PAYMENT
	ADD FOREIGN KEY (BID_NUMBER)
	REFERENCES BID (BID_NUMBER)
;


ALTER TABLE B_ANSWER
	ADD FOREIGN KEY (B_NUM)
	REFERENCES BOARD (B_NUM)
;


ALTER TABLE AUCTION
	ADD FOREIGN KEY (C_NUM)
	REFERENCES CATEGORY (C_NUM)
;


ALTER TABLE BID
	ADD FOREIGN KEY (M_NUM)
	REFERENCES MEMBERS (M_NUM)
;


ALTER TABLE BOARD
	ADD FOREIGN KEY (M_NUM)
	REFERENCES MEMBERS (M_NUM)
;


ALTER TABLE INTERPRODUCT
	ADD FOREIGN KEY (M_NUM)
	REFERENCES MEMBERS (M_NUM)
;


ALTER TABLE QUESTION
	ADD FOREIGN KEY (M_NUM)
	REFERENCES MEMBERS (M_NUM)
;


ALTER TABLE SELLER
	ADD FOREIGN KEY (M_NUM)
	REFERENCES MEMBERS (M_NUM)
;


ALTER TABLE SINGO
	ADD FOREIGN KEY (M_NUM)
	REFERENCES MEMBERS (M_NUM)
;


ALTER TABLE ANSWER
	ADD FOREIGN KEY (QUE_NUM)
	REFERENCES QUESTION (QUE_NUM)
;


ALTER TABLE AUCTION
	ADD FOREIGN KEY (SEL_NUMBER)
	REFERENCES SELLER (SEL_NUMBER)
;


ALTER TABLE SINGO
	ADD FOREIGN KEY (SEL_NUMBER)
	REFERENCES SELLER (SEL_NUMBER)
;



/* Create Triggers */

CREATE OR REPLACE TRIGGER TRI_AUCTION_A_NUM BEFORE INSERT ON AUCTION
FOR EACH ROW
BEGIN
	SELECT SEQ_AUCTION_A_NUM.nextval
	INTO :new.A_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_BID_BID_NUMBER BEFORE INSERT ON BID
FOR EACH ROW
BEGIN
	SELECT SEQ_BID_BID_NUMBER.nextval
	INTO :new.BID_NUMBER
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_BOARD_B_NUM BEFORE INSERT ON BOARD
FOR EACH ROW
BEGIN
	SELECT SEQ_BOARD_B_NUM.nextval
	INTO :new.B_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_CATEGORY_C_NUM BEFORE INSERT ON CATEGORY
FOR EACH ROW
BEGIN
	SELECT SEQ_CATEGORY_C_NUM.nextval
	INTO :new.C_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_MEMBERS_M_NUM BEFORE INSERT ON MEMBERS
FOR EACH ROW
BEGIN
	SELECT SEQ_MEMBERS_M_NUM.nextval
	INTO :new.M_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_MEMBER_M_NUM BEFORE INSERT ON MEMBER
FOR EACH ROW
BEGIN
	SELECT SEQ_MEMBER_M_NUM.nextval
	INTO :new.M_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_PAYMENT_PAY_NUM BEFORE INSERT ON PAYMENT
FOR EACH ROW
BEGIN
	SELECT SEQ_PAYMENT_PAY_NUM.nextval
	INTO :new.PAY_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_QNA_QNA_NUM BEFORE INSERT ON QNA
FOR EACH ROW
BEGIN
	SELECT SEQ_QNA_QNA_NUM.nextval
	INTO :new.QNA_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_QUESTION_QNA_NUM BEFORE INSERT ON QUESTION
FOR EACH ROW
BEGIN
	SELECT SEQ_QUESTION_QNA_NUM.nextval
	INTO :new.QNA_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_QUESTION_QUE_NUM BEFORE INSERT ON QUESTION
FOR EACH ROW
BEGIN
	SELECT SEQ_QUESTION_QUE_NUM.nextval
	INTO :new.QUE_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_SELLER_SEL_NUMBER BEFORE INSERT ON SELLER
FOR EACH ROW
BEGIN
	SELECT SEQ_SELLER_SEL_NUMBER.nextval
	INTO :new.SEL_NUMBER
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_SHIP_S_NUM BEFORE INSERT ON SHIP
FOR EACH ROW
BEGIN
	SELECT SEQ_SHIP_S_NUM.nextval
	INTO :new.S_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_SINGO_PENALTY_NUM BEFORE INSERT ON SINGO
FOR EACH ROW
BEGIN
	SELECT SEQ_SINGO_PENALTY_NUM.nextval
	INTO :new.PENALTY_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_SINGO_SINGO_NUM BEFORE INSERT ON SINGO
FOR EACH ROW
BEGIN
	SELECT SEQ_SINGO_SINGO_NUM.nextval
	INTO :new.SINGO_NUM
	FROM dual;
END;

/




/* Comments */

COMMENT ON COLUMN ANSWER.B_CONTENT IS '제목은 답변입니다로 통일';
COMMENT ON COLUMN AUCTION.BIDSTATUS IS '0 : 입찰전
1 : 입찰중
2 : 거래중
3 : 거래완료';
COMMENT ON COLUMN AUCTION.A_BIDUNIT IS '경매 입찰 단위';
COMMENT ON COLUMN BID.BID_DATE IS 'SYSTIMESTAMP';
COMMENT ON COLUMN BOARD.B_STATUS IS '0 : 미답변
1 : 완료';
COMMENT ON COLUMN B_ANSWER.B_CONTENT IS '제목은 답변입니다로 통일';
COMMENT ON COLUMN MEMBERS.M_ID IS '영어랑 숫자만 입력가능
(최소 6, 최대 12글자)';
COMMENT ON COLUMN MEMBERS.TRUST IS '신뢰도 시작 : 5
정상거래시 +1
신고 및 비매너 거래 -1';
COMMENT ON COLUMN MEMBERS.M_TYPE IS '0:회원
1:탈퇴한 회원';
COMMENT ON COLUMN PAYMENT.PAY_STATUS IS '0: 미입금
1 : 입금완료';
COMMENT ON COLUMN QUESTION.QUE_STATUS IS '미답변 : 0
답변 : 1';
COMMENT ON COLUMN SINGO.SINGO_STATUS IS '0 : 처리전
1 : 처리함
2 : 처리 반려';
COMMENT ON COLUMN SINGO.SINGO_DATE IS '신고한 날짜';



